//Cos'è un algoritmo?

//l'algoritmo è un insieme di step per la risoluzione del problema.




//Cos'è una variabile?

//Una variabile possiamo immaginarla come una scatola, che sia etichettata con un nome, e che abbia al suo interno un contenuto che viene conservato.
//al suo interno possiamo inserire qualsiasi contenuto o valore, e possiamo anche cambiarlo tutte le volte che ne abbiamo bisogno 






//Undefined e null sono la stessa cosa?

//Undefined e null non sono la stessa cosa. La differenza tra i due e che undefined rappresenta il contenuto di una variabile a cui non e mai stato
// assegnato un valore, mentre null rappresenta un non-valore intensionalmente assegnato dal programmatore.